- hosts: localhost
  become: true
  tasks: 
    - name: Install zsh
      apt: name=zsh
    - name: Change shell
      shell: chsh -s `which zsh`
    # - name: Install ohmyzsh(pls don't tell people )
    #   shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    # - name: Install autosuggestions
    #   ansible.builtin.git:
    #       repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' 
    #       dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    # - name: update our zshrc
    #   shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
    - name: install node
      apt:
         name: ['nodejs', 'npm']
    - name: Install n
      npm: name=n
    - name: n 14
      shell: n 14
